### ISSUE TITLE
Найти наилучший ORM для работы с БД

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#13]
В данный момент используется psycopg с нативными запросами. 
Поискать что подойдет для проекта лучше всего, может какой нибудь SQLAlchemy или peewee. Или может стоит оставить как есть, вообщем рисерч.

**Comment by demidovakatya** [comment]
@REDNBLACK, в чем минусы sql по сравнению с orm?

**Comment by REDNBLACK** [comment]
@demidovakatya Невозможно переиспользовать код.

Тут минусы скорее в psycopg, в нем очень неудобно создавать соединения к базе и выполнять запросы, с какой нибудь оберткой будет проще выполнять даже нативные SQL запросы.

**Comment by REDNBLACK** [comment]
@demidovakatya будет чистый psycopg
