### ISSUE TITLE
Edit bot info via BotFather

### ISSUE THREAD

**Issue by demidovakatya** [telegram-bots/telegram-channels-feed#22]
Чекнуть на адекватность свежим взглядом.

- [x] description
- [x] photo
- [x] about
- [x]  commands:
- subscribe
- unsubscribe
- help
- list

**Comment by REDNBLACK** [comment]
Добавить описание для команды `export`

**Comment by REDNBLACK** [comment]
Обновить https://github.com/telegram-bots/telegram-channels-feed/blob/master/bot/resources/info/help.txt
