### ISSUE TITLE
Отсылать обновления постов как новые посты

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#32]
Старые посты НЕ удалять.

**Comment by REDNBLACK** [comment]
Частично сделано, осталось понять как отсылать обновления.

**Comment by REDNBLACK** [comment]
Готово https://github.com/telegram-bots/telegram-channels-feed/commit/5c67d97ad84a11a5005a8a6b470b6053df285a2f

**Comment by demidovakatya** [comment]
#44 – следствие этой задачи :с

Мне не нравится, что будут приходить лишние сообщения. Нет вообще других способов, да?
