### ISSUE TITLE
Реализовать обработку дополнительных  типов сообщений

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#33]
А именно (по приоритету):
* Файл
* Видео
* Аудио
* Стикер

**Comment by REDNBLACK** [comment]
@demidovakatya что думаешь? стоит ли вообще заморачиваться?

**Comment by REDNBLACK** [comment]
Может просто писать так? :

`new sticker/file/audio/video in channel_name`

**Comment by REDNBLACK** [comment]
Хотя, возможно стикер можно отослать как фото.

**Comment by demidovakatya** [comment]
Заморачиваться так сильно я бы пока не стала, тбх.

**Comment by REDNBLACK** [comment]
оставим пока как есть
