### ISSUE TITLE
Удалять подписки пользователя спустя 24 часа после блока бота

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#37]
Если пользователь заблочил бота, мы детектим это и ставим ему таймер на 24 часа. По истечении таймера, если так и не удалось отправить посты, то удаляем все подписки пользователя (ну и самого пользователя). Если удалось, то удаляем таймер.

**Comment by demidovakatya** [comment]
Why?

**Comment by REDNBLACK** [comment]
я уже объяснял почему

**Comment by REDNBLACK** [comment]
48 часов

**Comment by demidovakatya** [comment]
как насчёт `/mute`?

**Comment by REDNBLACK** [comment]
Так ведь речь как раз о людях, которые просто заблокируют бота и перестанут им пользоваться.
Из-за этого очередь будет заполнена их подписками, которые так никогда и не будут отправлены.

А `/mute` - это уже отдельный функционал

**Comment by demidovakatya** [comment]
может, добавить кнопку или функцию **stop bot**? 
а после выбора кнопки/функции **stop bot** юзеру будет предлагаться: сразу, через 12 часов, через 24 часа.

в общем хелпе предупреждать, что по умолчанию даётся 12 часов, но на всякий случай можно в настройках увеличить «период на раздумья» до 24 ч

**Comment by REDNBLACK** [comment]
хорошая идея

**Comment by REDNBLACK** [comment]
redundant
