### ISSUE TITLE
Добавить сортировку к выводимым каналам по команде /list

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#39]
В порядке добавления (?)

**Comment by demidovakatya** [comment]
https://github.com/telegram-bots/telegram-channels-feed/commit/44d3e10e4ee4943601c3d61060a46332e875cc52

добавила сортировку по имени.

**Comment by REDNBLACK** [comment]
применено и работает

**Comment by demidovakatya** [comment]
мб, нужно по адресу канала сортировать?

**Comment by REDNBLACK** [comment]
можно попробовать
