### ISSUE TITLE
Ошибка с форматированием вложенных тегов (<b>, <i> итд)

### ISSUE THREAD

**Issue by REDNBLACK** [telegram-bots/telegram-channels-feed#41]
В [спецификации](https://core.telegram.org/bots/api#formatting-options) написано:
- Tags must not be nested

Но в сообщениях из каналов тэги могут быть легко вложены друг в друга.
Надо это как-то исправлять.

**Comment by demidovakatya** [comment]
@REDNBLACK мне кажется, это баг телеграма. Нужно исправлять эту неконсистентность, имхо.

**Comment by REDNBLACK** [comment]
Fixed https://github.com/telegram-bots/telegram-channels-feed/commit/671945756f7115e03378a86fecdeac073aa068cd

**Comment by REDNBLACK** [comment]
Нее, не исправлено. Откатил изменения https://github.com/telegram-bots/telegram-channels-feed/commit/338e19490fc85d4a4fa2d417d6f9a897e28cd915

**Comment by REDNBLACK** [comment]
... Теперь понятно
