### ISSUE TITLE
Настройки: вид ленты

### ISSUE THREAD

**Issue by demidovakatya** [telegram-bots/telegram-channels-feed#45]
Предлагаю позволить пользователю настраивать внешний вид ленты: 
* как сейчас – полные посты,
* только заголовки (ссылка на пост в канал)
* опционально: короткое превью 
* опционально, нужно подумать: ничего (на мой взгляд, такой режим нужно сделать доступным онли для тех, кто экспортирует ленту в канал)

**Comment by REDNBLACK** [comment]
Разделено на задачи https://github.com/telegram-bots/telegram-channels-feed/projects/3
Эту закрываю
