### ISSUE TITLE
Еще работает?

### ISSUE THREAD

**Issue by mrtheyann** [telegram-bots/telegram-channels-feed#52]
Привет, возникла потребность в подобном боте, ваш еще где-то хостится и доступен или придётся написать своего?)

**Comment by REDNBLACK** [comment]
привет, нет не хостится и не доступен, но знаю что существуют аналоги с платой по подписке

**Comment by mrtheyann** [comment]
тогда накидаю свой и захощу на хероку, спасибо за ответ)
